import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../api/client'
import { useAuth } from '../api/AuthContext'

type Cert = {
  certificateId: string
  studentName: string
  courseName: string
  brandName: string
  level: string
  fieldOfStudy: string
  duration: string
  mode: string
  skills: string
  grade: string
  projectTitle?: string
  issueDate: string
  verificationUrl: string
  qrCodeUrl?: string
}

export function CertificatePage() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [certs, setCerts] = useState<Cert[]>([])
  const [selected, setSelected] = useState<Cert | null>(null)
  const [slug, setSlug] = useState('ai-fundamentals')
  const [error, setError] = useState('')

  const load = () => {
    if (!user) return
    api<Cert[]>('/certificates/mine')
      .then((list) => {
        setCerts(list)
        setSelected(list[0] ?? null)
      })
      .catch(() => undefined)
  }

  useEffect(() => {
    if (!user) {
      navigate('/login')
      return
    }
    load()
  }, [user, navigate])

  const generate = async () => {
    setError('')
    try {
      const cert = await api<Cert>(`/certificates/generate/${slug}`, { method: 'POST' })
      setSelected(cert)
      load()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not generate certificate')
    }
  }

  return (
    <>
      <section className="page-hero">
        <div className="container">
          <span className="eyebrow" style={{ color: 'var(--secondary)' }}>
            Certificate System
          </span>
          <h1>Certificate of Completion</h1>
          <p>
            Digitally generated by Prime Digital Academy. Verify authenticity with Certificate ID or QR
            verification URL.
          </p>
        </div>
      </section>

      <section className="section" style={{ paddingTop: '2rem' }}>
        <div className="container">
          <div className="contact-grid" style={{ marginBottom: '1.5rem' }}>
            <div className="form-field">
              <label htmlFor="slug">Generate for completed course slug</label>
              <input id="slug" value={slug} onChange={(e) => setSlug(e.target.value)} />
            </div>
            <div style={{ display: 'flex', alignItems: 'end', gap: '0.75rem' }}>
              <button type="button" className="btn btn-primary" onClick={generate}>
                Generate certificate
              </button>
              <button type="button" className="btn btn-ghost" onClick={() => window.print()}>
                Download / Print
              </button>
            </div>
          </div>
          {error && <p style={{ color: 'crimson', fontWeight: 600 }}>{error}</p>}
          {certs.length > 1 && (
            <div className="filters" style={{ marginBottom: '1rem' }}>
              {certs.map((c) => (
                <button
                  key={c.certificateId}
                  type="button"
                  className={`chip ${selected?.certificateId === c.certificateId ? 'active' : ''}`}
                  onClick={() => setSelected(c)}
                >
                  {c.courseName}
                </button>
              ))}
            </div>
          )}

          {!selected ? (
            <div className="empty">
              No certificates yet. Complete a course in the <Link to="/dashboard">learning portal</Link>, then generate.
            </div>
          ) : (
            <div className="certificate">
              <div className="seal">PIN</div>
              <h1>Prime Digital Academy</h1>
              <p style={{ color: 'var(--muted)', marginBottom: '0.25rem' }}>
                Powered by {selected.brandName}
              </p>
              <h2>Certificate of Completion</h2>
              <p>This is to certify that</p>
              <div className="recipient">{selected.studentName}</div>
              <p>
                has successfully completed the program{' '}
                <strong style={{ color: 'var(--primary)' }}>{selected.courseName}</strong> offered by Prime Digital
                Academy, having fulfilled all the academic and practical requirements of the course.
              </p>

              <div className="cert-grid">
                <div>
                  <b>Course Level:</b> {selected.level}
                </div>
                <div>
                  <b>Field of Study:</b> {selected.fieldOfStudy}
                </div>
                <div>
                  <b>Duration:</b> {selected.duration}
                </div>
                <div>
                  <b>Mode of Learning:</b> {selected.mode}
                </div>
                <div>
                  <b>Date of Completion:</b> {new Date(selected.issueDate).toLocaleDateString()}
                </div>
                <div>
                  <b>Grade/Score:</b> {selected.grade}
                </div>
              </div>

              <p style={{ fontSize: '0.95rem' }}>
                <b>Skills Acquired:</b> {selected.skills}
              </p>

              <p style={{ fontSize: '0.9rem' }}>
                Certificate ID: <b>{selected.certificateId}</b>
                <br />
                Verification URL: {selected.verificationUrl}
              </p>

              {selected.qrCodeUrl && (
                <div style={{ margin: '1.25rem 0' }}>
                  <img
                    src={selected.qrCodeUrl}
                    alt={`QR code for certificate ${selected.certificateId}`}
                    width={160}
                    height={160}
                    style={{ margin: '0 auto' }}
                  />
                  <p style={{ fontSize: '0.85rem', marginTop: '0.5rem' }}>Scan to verify authenticity</p>
                </div>
              )}

              <div className="sign-row">
                <div>
                  <div className="sign-line">
                    Director, Prime Digital Academy
                    <br />
                    Dr. Ngozi Adewale
                  </div>
                </div>
                <div>
                  <div className="sign-line">
                    Program Coordinator
                    <br />
                    Funke Adebayo
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </section>
    </>
  )
}
